// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	authservice "github.com/pakkaparn/no-idea-api/internal/services/authservice"
	mock "github.com/stretchr/testify/mock"
)

// AuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type AuthServiceInterface struct {
	mock.Mock
}

// GenerateToken provides a mock function with given fields: c
func (_m *AuthServiceInterface) GenerateToken(c authservice.Claimer) (string, error) {
	ret := _m.Called(c)

	var r0 string
	if rf, ok := ret.Get(0).(func(authservice.Claimer) string); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(authservice.Claimer) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthServiceInterface creates a new instance of AuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthServiceInterface(t mockConstructorTestingTNewAuthServiceInterface) *AuthServiceInterface {
	mock := &AuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
