// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	fieldservice "github.com/maetad/baroness-api/internal/services/fieldservice"
	mock "github.com/stretchr/testify/mock"

	model "github.com/maetad/baroness-api/internal/model"
)

// FieldServiceInterface is an autogenerated mock type for the FieldServiceInterface type
type FieldServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: r, creator
func (_m *FieldServiceInterface) Create(r fieldservice.FieldCreateRequest, creator *model.User) (*model.Field, error) {
	ret := _m.Called(r, creator)

	var r0 *model.Field
	if rf, ok := ret.Get(0).(func(fieldservice.FieldCreateRequest, *model.User) *model.Field); ok {
		r0 = rf(r, creator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Field)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(fieldservice.FieldCreateRequest, *model.User) error); ok {
		r1 = rf(r, creator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: field, deletor
func (_m *FieldServiceInterface) Delete(field *model.Field, deletor *model.User) error {
	ret := _m.Called(field, deletor)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.Field, *model.User) error); ok {
		r0 = rf(field, deletor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *FieldServiceInterface) Get(id uint) (*model.Field, error) {
	ret := _m.Called(id)

	var r0 *model.Field
	if rf, ok := ret.Get(0).(func(uint) *model.Field); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Field)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: workflowID
func (_m *FieldServiceInterface) List(workflowID uint) ([]model.Field, error) {
	ret := _m.Called(workflowID)

	var r0 []model.Field
	if rf, ok := ret.Get(0).(func(uint) []model.Field); ok {
		r0 = rf(workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Field)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: field, r, updator
func (_m *FieldServiceInterface) Update(field *model.Field, r fieldservice.FieldUpdateRequest, updator *model.User) (*model.Field, error) {
	ret := _m.Called(field, r, updator)

	var r0 *model.Field
	if rf, ok := ret.Get(0).(func(*model.Field, fieldservice.FieldUpdateRequest, *model.User) *model.Field); ok {
		r0 = rf(field, r, updator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Field)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.Field, fieldservice.FieldUpdateRequest, *model.User) error); ok {
		r1 = rf(field, r, updator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFieldServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFieldServiceInterface creates a new instance of FieldServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFieldServiceInterface(t mockConstructorTestingTNewFieldServiceInterface) *FieldServiceInterface {
	mock := &FieldServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
