// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileServiceInterface is an autogenerated mock type for the FileServiceInterface type
type FileServiceInterface struct {
	mock.Mock
}

// Upload provides a mock function with given fields: file, filename
func (_m *FileServiceInterface) Upload(file []byte, filename string) (string, error) {
	ret := _m.Called(file, filename)

	var r0 string
	if rf, ok := ret.Get(0).(func([]byte, string) string); ok {
		r0 = rf(file, filename)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte, string) error); ok {
		r1 = rf(file, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewFileServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewFileServiceInterface creates a new instance of FileServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFileServiceInterface(t mockConstructorTestingTNewFileServiceInterface) *FileServiceInterface {
	mock := &FileServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
