// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	model "github.com/maetad/baroness-api/internal/model"
	stateservice "github.com/maetad/baroness-api/internal/services/stateservice"
	mock "github.com/stretchr/testify/mock"
)

// StateServiceInterface is an autogenerated mock type for the StateServiceInterface type
type StateServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: r, creator
func (_m *StateServiceInterface) Create(r stateservice.StateCreateRequest, creator *model.User) (*model.State, error) {
	ret := _m.Called(r, creator)

	var r0 *model.State
	if rf, ok := ret.Get(0).(func(stateservice.StateCreateRequest, *model.User) *model.State); ok {
		r0 = rf(r, creator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(stateservice.StateCreateRequest, *model.User) error); ok {
		r1 = rf(r, creator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: state, deletor
func (_m *StateServiceInterface) Delete(state *model.State, deletor *model.User) error {
	ret := _m.Called(state, deletor)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.State, *model.User) error); ok {
		r0 = rf(state, deletor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: id
func (_m *StateServiceInterface) Get(id uint) (*model.State, error) {
	ret := _m.Called(id)

	var r0 *model.State
	if rf, ok := ret.Get(0).(func(uint) *model.State); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: workflowID
func (_m *StateServiceInterface) List(workflowID uint) ([]model.State, error) {
	ret := _m.Called(workflowID)

	var r0 []model.State
	if rf, ok := ret.Get(0).(func(uint) []model.State); ok {
		r0 = rf(workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: state, r, updator
func (_m *StateServiceInterface) Update(state *model.State, r stateservice.StateUpdateRequest, updator *model.User) (*model.State, error) {
	ret := _m.Called(state, r, updator)

	var r0 *model.State
	if rf, ok := ret.Get(0).(func(*model.State, stateservice.StateUpdateRequest, *model.User) *model.State); ok {
		r0 = rf(state, r, updator)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.State)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.State, stateservice.StateUpdateRequest, *model.User) error); ok {
		r1 = rf(state, r, updator)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewStateServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewStateServiceInterface creates a new instance of StateServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewStateServiceInterface(t mockConstructorTestingTNewStateServiceInterface) *StateServiceInterface {
	mock := &StateServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
