// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// UserServiceDatabaseInterface is an autogenerated mock type for the UserServiceDatabaseInterface type
type UserServiceDatabaseInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: value
func (_m *UserServiceDatabaseInterface) Create(value interface{}) *gorm.DB {
	ret := _m.Called(value)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(interface{}) *gorm.DB); ok {
		r0 = rf(value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

type mockConstructorTestingTNewUserServiceDatabaseInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserServiceDatabaseInterface creates a new instance of UserServiceDatabaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserServiceDatabaseInterface(t mockConstructorTestingTNewUserServiceDatabaseInterface) *UserServiceDatabaseInterface {
	mock := &UserServiceDatabaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
